name: Publish README.pdf

on: [push]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.0.0
      - name: Generate README.pdf
        uses: rseng/pdf-generator@v0.0.4
        with:
          paper_markdown: README.md
          paper_outfile: README.pdf
          pdf_type: minimal
      - name: Commit README.pdf
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Publish README.pdf
          file_pattern: README.pdf
