name: Publish README.pdf

on: [push]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.0.0
      - name: Generate README.pdf
        uses: scottypate/md-to-pdf@slashformotion:master
        env: {
          PDF_DIR: './'
        }
      - name: Commit README.pdf
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Publish README.pdf
          file_pattern: README.pdf
