name: Publish README.pdf

on: [push]

jobs:
  publish-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm i -g md-to-pdf
      - run: md-to-pdf -- README.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Publish README.pdf
          file_pattern: README.pdf
